apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: uznfqv7km-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/uznfqv7km-java-quarkus-gitops